set dotenv-load := true
set shell := ["bash", "-cu"]

serve:
	uv run -m app

tests +args="":
	uv run pytest {{args}}

test-migrations:
    #!/bin/sh
    export PGDATA="$(mktemp -d)"
    export PG__PORT=6666
    export INIT_DB_OPTIONS="-p ${PG__PORT}"
    export PG__DBNAME="${TEST_DBNAME}"
    export PG_URL="postgresql+asyncpg://${PG__USER}:${PG__PASSWORD}@${PG__HOST}:${PG__PORT}/${PG__DBNAME}"
    echo "stopping any existing instance"
    just stop-db || true
    echo "Starting test postgres server with ${PGDATA}"
    just start-db
    just create-test-db
    just alembic upgrade head
    just alembic downgrade base
    echo "Cleaning up"
    just stop-db
    rm -rf "${PGDATA}"
    echo "Stopped postgres server. Do not forget to run start-db with your own PGDATA to restart"

alembic +args:
    uv run alembic {{args}}

start-db:
    if [ ! -f "${PGDATA}/PG_VERSION" ]; then initdb -D "${PGDATA}" -U ${PG__USER}; fi
    pg_ctl -o "${INIT_DB_OPTIONS}" -D "${PGDATA}" start

stop-db:
    pg_ctl -D ${PGDATA} stop

create-db-user:
    createuser -s ${PG__USER}

create-db:
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -tc "SELECT 1 FROM pg_database WHERE datname='${PG__DBNAME}'" | \
        grep -q 1 || \
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -c "CREATE DATABASE ${PG__DBNAME};"

drop-db:
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -c "DROP DATABASE IF EXISTS ${PG__DBNAME};"

create-test-db:
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -tc "SELECT 1 FROM pg_database WHERE datname='${TEST_DBNAME}'" | \
        grep -q 1 || \
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -c "CREATE DATABASE ${TEST_DBNAME};"

drop-test-db:
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -c "DROP DATABASE IF EXISTS ${TEST_DBNAME};"
