set dotenv-load := true

serve:
	uv run -m app

tests +args="":
	uv run pytest {{args}}

alembic +args:
	alembic {{args}}

start-db:
    if [ ! -f "${PGDATA}/PG_VERSION" ]; then initdb -D "${PGDATA}" -U ${PG__USER}; fi
    pg_ctl -o "${INIT_DB_OPTIONS}" -D "${PGDATA}" start

stop-db:
    pg_ctl -D ${PGDATA} stop

create-db-user:
    createuser -s ${PG__USER}

create-db:
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -tc "SELECT 1 FROM pg_database WHERE datname='${PG__DBNAME}'" | \
        grep -q 1 || \
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -c "CREATE DATABASE ${PG__DBNAME};"

drop-db:
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -c "DROP DATABASE IF EXISTS ${PG__DBNAME};"

create-test-db:
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -tc "SELECT 1 FROM pg_database WHERE datname='${TEST_DBNAME}'" | \
        grep -q 1 || \
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -c "CREATE DATABASE ${TEST_DBNAME};"

drop-test-db:
    psql -h ${PG__HOST} -p ${PG__PORT} -U ${PG__USER} \
        -c "DROP DATABASE IF EXISTS ${TEST_DBNAME};"
